/**
 * Rotas centralizadas do app.
 * Use ROUTES para Link/navigate; use ROUTE_PATHS para <Route path={...} /> (segmentos relativos ao parent).
 */
export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  PRODUCT: (id: string) => `/produto/${id}`,
  CART: '/carrinho',
  WISHLIST: '/favoritos',
  POLICY_PRIVACY: '/politica-privacidade',
  POLICY_DELIVERY: '/politica-entrega',
  POLICY_RETURNS: '/trocas',
  PAYMENT_SUCCESS: '/pagamento/sucesso',
  PAYMENT_FAILURE: '/pagamento/falha',
  PAYMENT_PENDING: '/pagamento/pendente',
  CONTACT: '/contato',
  ABOUT: '/sobre',
  WORK_WITH_US: '/trabalhe-conosco',
  FAQ: '/faq',
  ADMIN: '/admin',
  ADMIN_ORDERS: '/admin/pedidos',
  ADMIN_PRODUCTS: '/admin/produtos',
  ADMIN_BANNERS: '/admin/banners',
  ADMIN_USERS: '/admin/usuarios',
  ADMIN_SETTINGS: '/admin/configuracoes',
  ADMIN_CHAT: '/admin/chat',
  ADMIN_AI_SETTINGS: '/admin/ai-settings',
  ACCOUNT: '/conta',
  ORDERS: '/meus-pedidos',
} as const;

/** Segmentos de path para <Route path="..." /> (sem barra inicial). */
export const ROUTE_PATHS = {
  HOME: '',
  LOGIN: 'login',
  ACCOUNT: 'conta',
  PRODUCT: 'produto/:id',
  CART: 'carrinho',
  WISHLIST: 'favoritos',
  POLICY_PRIVACY: 'politica-privacidade',
  POLICY_DELIVERY: 'politica-entrega',
  POLICY_RETURNS: 'trocas',
  PAYMENT_SUCCESS: 'pagamento/sucesso',
  PAYMENT_FAILURE: 'pagamento/falha',
  PAYMENT_PENDING: 'pagamento/pendente',
  ADMIN: 'admin',
  ADMIN_ORDERS: 'pedidos',
  ADMIN_PRODUCTS: 'produtos',
  ADMIN_BANNERS: 'banners',
  ADMIN_USERS: 'usuarios',
  ADMIN_SETTINGS: 'configuracoes',
  ADMIN_CHAT: 'chat',
  ADMIN_AI_SETTINGS: 'ai-settings',
  ORDERS: 'meus-pedidos',
} as const;
